{% set name = "colcon-common-extensions" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: f3b2e939f201e949486324cb0145216be478b7160d882017c5fb4210851cd316

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
  run:
    - python
    - colcon-cmake
    - colcon-core
    - colcon-defaults
    - colcon-devtools
    - colcon-library-path
    - colcon-metadata
    - colcon-notification  # [win]
    - colcon-output
    - colcon-package-information
    - colcon-package-selection
    - colcon-parallel-executor
    - colcon-powershell
    - colcon-python-setup-py
    - colcon-recursive-crawl
    - colcon-ros
    - colcon-test-result
    - colcon-argcomplete  # [not win]
    - colcon-cd  # [not win]
    - colcon-bash  # [not win]
    - colcon-zsh  # [not win]

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    A meta package aggregating colcon-core as well as a set of common extensions.

extra:
  recipe-maintainers:
    - j-rivero
    - traversaro
    - seanyen
    - wolfv
