{% set name = "colcon-common-extensions" %}
{% set version = "0.2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://github.com/colcon/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 83d8f06ef2d815456ac627ee5789ac752f74036897c422834c6b478c9063a281

build:
  number: 2
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [py<35]

requirements:
  host:
    - pip
    - python
  run:
    - python
    - colcon-cmake
    - colcon-core
    - colcon-defaults
    - colcon-devtools
    - colcon-library-path
    - colcon-metadata
    - colcon-notification  # [win]
    - colcon-output
    - colcon-package-information
    - colcon-package-selection
    - colcon-parallel-executor
    - colcon-powershell
    - colcon-python-setup-py
    - colcon-recursive-crawl
    - colcon-ros
    - colcon-test-result

test:
  imports:
    - {{ name.replace("-", "_") }}

about:
  home: https://github.com/colcon/{{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    A meta package aggregating colcon-core as well as a set of common extensions.

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
