schema_version: 1

context:
  name: colcon-common-extensions
  version: "0.3.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/colcon/${{ name }}/archive/${{ version }}.tar.gz
  sha256: f3b2e939f201e949486324cb0145216be478b7160d882017c5fb4210851cd316

build:
  number: 5
  script: python -m pip install . -vv

requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - colcon-cmake
    - colcon-core
    - colcon-defaults
    - colcon-devtools
    - colcon-library-path
    - colcon-metadata
    - if: win
      then: colcon-notification
    - colcon-output
    - colcon-package-information
    - colcon-package-selection
    - colcon-parallel-executor
    - colcon-powershell
    - colcon-python-setup-py
    - colcon-recursive-crawl
    - colcon-ros
    - colcon-test-result
    - if: not win
      then:
        - colcon-argcomplete
        - colcon-cd
        - colcon-bash
        - colcon-zsh

tests:
  - python:
      imports:
        - colcon_common_extensions

about:
  homepage: https://github.com/colcon/${{ name }}
  license: Apache-2.0
  license_file: LICENSE
  summary: |
    A meta package aggregating colcon-core as well as a set of common extensions.

extra:
  recipe-maintainers:
    - j-rivero
    - traversaro
    - seanyen
    - wolfv
